M48
; DRILL file {KiCad 9.0.0} date 2025-03-03T21:56:56-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-03T21:56:56-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.290
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X105.65Y-84.19
X128.0Y-70.7
X128.0Y-97.67
T2
X68.94Y-69.49
X68.94Y-116.44
X93.45Y-69.49
X93.45Y-116.44
T3
X41.6Y-121.0
X84.2Y-30.8
X130.2Y-122.0
M30
